import type { Market } from "@/types/market";

export const creativeSeedMarkets: Market[] = [
  {
    id: "kale-001",
    title: "KALE reaches 2,000 holders this month?",
    description: "Community growth prediction for KALE holders by month end.",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 7,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-002",
    title: "First KALE DEX pair launched this quarter?",
    description: "Will a KALE trading pair go live on a Stellar DEX this quarter?",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 14,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-003",
    title: "KALE song reaches 10k plays?",
    description: "Will the iconic KALE song hit 10,000 plays across platforms?",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 10,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-004",
    title: "Top 100 leaderboard shuffle next week?",
    description: "Will at least 20 new addresses enter KALE top-100 by next week?",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 7,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-005",
    title: "Lazy farmer wins 3 blocks in a row?",
    description: "Automation claims 3 consecutive harvests within 48 hours.",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 2,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-006",
    title: "KALE Discord hits +2 new channels?",
    description: "Will two or more new KALE community channels be created this month?",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 20,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-007",
    title: "First KALE merch teaser drops?",
    description: "Will a KALE-branded merch teaser be posted this month?",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 15,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-008",
    title: "xBull wallet adds a KALE shortcut?",
    description: "Will any wallet UI add a KALE-specific quick action?",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 21,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-009",
    title: "New KALE meme trend appears?",
    description: "Will a new KALE meme format trend this week?",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 7,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-010",
    title: "KALE faucet prototype announced?",
    description: "Will a community faucet prototype for KALE be teased?",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 30,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-011",
    title: "KALE lore: new chapter release?",
    description: "Will a new Kale-on-Demeter lore chapter be released this month?",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 25,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-012",
    title: "10k KALE burned by community?",
    description: "Will a burn event of at least 10,000 KALE be executed this quarter?",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 60,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-013",
    title: "Weekly harvest record broken?",
    description: "Will the weekly highest harvest be broken this week?",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 7,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-014",
    title: "KALE Twitter post surpasses 1k likes?",
    description: "Will a KALE post surpass 1,000 likes this month?",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 30,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-015",
    title: "New KALE mini-game prototype shown?",
    description: "Will a KALE-themed mini-game prototype be publicly shown?",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 40,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
  {
    id: "kale-016",
    title: "KALE dev stream scheduled?",
    description: "Will there be a scheduled developer livestream about KALE this month?",
    creatorId: "seed",
    createdAt: Date.now(),
    closesAt: Date.now() + 1000 * 60 * 60 * 24 * 20,
    initialPool: 0,
    minBet: 0,
    maxBet: 0,
    status: "open",
    bets: [],
  },
];





